---
name: "vcorelib"
version: "{{major}}.{{minor}}.{{patch}}"
description: "A collection of core Python utilities."
requirements:
  - ruamel.yaml
  - tomli
  - tomli-w
dev_requirements:
  - pytest-asyncio
  - setuptools-wrapper
  - types-setuptools
init_local: |

  DEFAULT_INDENT = 2
  DEFAULT_ENCODING = "utf-8"
