---
name: "vcorelib"
version: "{{major}}.{{minor}}.{{patch}}"
description: "A collection of core Python utilities."

requirements:
  - aiofiles
  - cerberus
  - fastjsonschema
  - markdown
  - ruamel.yaml
  - tomli
  - tomli-w
  - importlib-resources

dev_requirements:
  - pytest-asyncio
  - setuptools-wrapper
  - types-setuptools
  - types-markdown
  - "uvloop; sys_platform != 'win32' and sys_platform != 'cygwin'"

init_local: |
  DEFAULT_INDENT = 2
  DEFAULT_ENCODING = "utf-8"

mypy_local: |
  [mypy-fastjsonschema.*]
  ignore_missing_imports = True

  [mypy-cerberus.*]
  ignore_missing_imports = True

  [mypy-aiofiles.*]
  ignore_missing_imports = True

  # Needed for windows.
  [mypy-uvloop.*]
  ignore_missing_imports = True
